language: shell

services:
  - docker

before_install:
  - pwd
  - export DOCKER_TAG=latest

script:
  - docker build -t naturalis/nba_scratchpad:$DOCKER_TAG ./

after_success:
  - docker login -u maartenschermer -p $DOCKER_PASS
  - docker tag naturalis/nba_scratchpad:$DOCKER_TAG naturalis/nba_scratchpad:$DOCKER_TAG
  - docker push naturalis/nba_scratchpad:$DOCKER_TAG
  - docker logout

branches:
  only:
  - master
